services:
  web:
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./html:/usr/share/nginx/html
    ports:
      - "8083:80"
      #- "443:443"
  #environment:
  # - NGINX_HOST=santi.app
  # - NGINX_PORT=443
